name: Systems@EPFL
url: http://systems.dslab.org

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty1
    name: Faculty
  - key: faculty2
    name: &nbsp
  - key: aff-faculty
    name: Affiliated Faculty
  - key: postdoc
    name: Postdocs
  - key: student
    name: Students
  - key: scientist
    name: Researchers
  - key: alum
    name: Latest PhD Alumni

# Number of news stories on the front page.
front_page_news: 5

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /people.html
  - title: Research
    link: /research.html
  - title: Publications
    link: /publications.html
  - title: Courses
    link: /courses.html
  - title: Seminar
    link: https://dslab.epfl.ch/syssem/
  # - title: Awards
  #   link: /awards.html
  # - title: Code
  #   link: /code.html
